version: '3'
services:
  app:
    image: ccr.ccs.tencentyun.com/bjd_bigdata/peak-flow-h5-front:${VERSION}
    environment:
      - ZUUL_HOST=zuul
      - ZUUL_PORT=8040
      - ZUUL_URL=http://zuul:8040
      - AUTH_ID=6c3a7833-16a1-42fb-905f-4e94b8985b79
      - NODE_PORT=8080
    ports:  
      - "9210:8080"
    networks:
      - springcloud-overlay
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
